/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email + password login → JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new tenant + owner, mint JWT */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user + resolved claims */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bump session version (force token refresh) */
        post: operations["bumpSessionVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthData: {
            /** @example ok */
            status: string;
            /** @example hivepos-api */
            service?: string;
            /** @example 0.1.0 */
            version?: string;
        };
        HealthEnvelope: components["schemas"]["EnvelopeSuccess"] & {
            data?: components["schemas"]["HealthData"];
        };
        UserInfo: {
            id: string;
            /** Format: email */
            email: string;
            name: string;
            /** @example OWNER */
            role: string;
            tenantId: string;
            branchId: string;
        };
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterInput: {
            tenantName: string;
            tenantSlug: string;
            ownerName: string;
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            module: "laundry" | "fnb" | "salon";
            branchName: string;
            phone?: string | null;
        };
        LoginResponse: {
            token: string;
            user: components["schemas"]["UserInfo"];
        };
        /** @description JWT claims resolved server-side, surfaced via /auth/me. */
        Claims: {
            tenantId?: string;
            branchId?: string;
            role?: string;
            permissions?: string[];
        };
        MeData: {
            user: components["schemas"]["UserInfo"];
            claims: components["schemas"]["Claims"];
        };
        SessionVersionData: {
            ok: boolean;
            sessionVersion: number;
        };
        EnvelopeSuccess: {
            /** @enum {boolean} */
            success: true;
            data: Record<string, never> | null;
            meta?: Record<string, never> | null;
        };
        LoginResponseEnvelope: components["schemas"]["EnvelopeSuccess"] & {
            data?: components["schemas"]["LoginResponse"];
        };
        MeEnvelope: components["schemas"]["EnvelopeSuccess"] & {
            data?: components["schemas"]["MeData"];
        };
        SessionVersionEnvelope: components["schemas"]["EnvelopeSuccess"] & {
            data?: components["schemas"]["SessionVersionData"];
        };
        ErrorBody: {
            code?: string;
            message: string;
        };
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            error: components["schemas"]["ErrorBody"];
        };
    };
    responses: {
        /** @description Validation error. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Credentials accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInput"];
            };
        };
        responses: {
            /** @description Tenant + owner created, logged in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session context. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    bumpSessionVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session version bumped. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionVersionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
